# Generated by Django 3.2.7 on 2021-10-19 00:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interaction',
            old_name='description',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='title',
        ),
        migrations.RemoveField(
            model_name='interaction',
            name='was_at',
        ),
        migrations.AddField(
            model_name='interaction',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='interaction',
            name='type',
            field=models.CharField(choices=[('call', 'Phone Call'), ('act', 'Activity'), ('rem', 'Reminder')], default='call', max_length=5),
        ),
    ]
