# Generated by Django 3.2.7 on 2021-10-22 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_auto_20211022_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='facebook',
            field=models.URLField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='instagram',
            field=models.URLField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='linkedin',
            field=models.URLField(blank=True, default='None', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='twitter',
            field=models.URLField(blank=True, default='None', max_length=120, null=True),
        ),
    ]
